[19/Jan/2022 19:59:02] INFO [django.utils.autoreload:617] Watching for file changes with StatReloader
[19/Jan/2022 19:59:02] INFO [django.utils.autoreload:617] Watching for file changes with StatReloader
[19/Jan/2022 19:59:05] INFO [django.server:157] "GET /application/address HTTP/1.1" 200 9835
[19/Jan/2022 19:59:05] INFO [django.server:157] "GET /application/address HTTP/1.1" 200 9835
[19/Jan/2022 19:59:06] INFO [django.server:157] "GET /static/application/styles_app.css HTTP/1.1" 200 17555
[19/Jan/2022 19:59:06] INFO [django.server:157] "GET /static/application/styles_app.css HTTP/1.1" 200 17555
[19/Jan/2022 19:59:06] INFO [django.server:157] "GET /static/application/images/BackArrow-white.svg HTTP/1.1" 200 798
[19/Jan/2022 19:59:06] INFO [django.server:157] "GET /static/application/images/BackArrow-white.svg HTTP/1.1" 200 798
[19/Jan/2022 19:59:06] INFO [django.server:157] "GET /static/application/images/BackArrow-darkblue.svg HTTP/1.1" 200 801
[19/Jan/2022 19:59:06] INFO [django.server:157] "GET /static/application/images/BackArrow-darkblue.svg HTTP/1.1" 200 801
[19/Jan/2022 19:59:06] WARNING [django.request:224] Not Found: /favicon.ico
[19/Jan/2022 19:59:06] WARNING [django.request:224] Not Found: /favicon.ico
[19/Jan/2022 19:59:06] WARNING [django.server:157] "GET /favicon.ico HTTP/1.1" 404 2878
[19/Jan/2022 19:59:06] WARNING [django.server:157] "GET /favicon.ico HTTP/1.1" 404 2878
[19/Jan/2022 19:59:11] INFO [django.server:157] "POST /application/address HTTP/1.1" 302 0
[19/Jan/2022 19:59:11] INFO [django.server:157] "POST /application/address HTTP/1.1" 302 0
[19/Jan/2022 19:59:12] ERROR [django.request:224] Internal Server Error: /application/addressCorrection
Traceback (most recent call last):
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JAndr\OneDrive\Projects\GetYourConnexion\DigitalEquity_MobileVers\mobileVers\application\views.py", line 326, in addressCorrection
    if 'ReturnText' in dict_address['AddressValidateResponse']['Address'].keys():
UnboundLocalError: local variable 'dict_address' referenced before assignment
[19/Jan/2022 19:59:12] ERROR [django.request:224] Internal Server Error: /application/addressCorrection
Traceback (most recent call last):
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JAndr\OneDrive\Projects\GetYourConnexion\DigitalEquity_MobileVers\mobileVers\application\views.py", line 326, in addressCorrection
    if 'ReturnText' in dict_address['AddressValidateResponse']['Address'].keys():
UnboundLocalError: local variable 'dict_address' referenced before assignment
[19/Jan/2022 19:59:12] ERROR [django.server:157] "GET /application/addressCorrection HTTP/1.1" 500 71344
[19/Jan/2022 19:59:12] ERROR [django.server:157] "GET /application/addressCorrection HTTP/1.1" 500 71344
[19/Jan/2022 20:00:59] INFO [django.utils.autoreload:240] C:\Users\JAndr\OneDrive\Projects\GetYourConnexion\DigitalEquity_MobileVers\mobileVers\application\views.py changed, reloading.
[19/Jan/2022 20:00:59] INFO [django.utils.autoreload:240] C:\Users\JAndr\OneDrive\Projects\GetYourConnexion\DigitalEquity_MobileVers\mobileVers\application\views.py changed, reloading.
